### ISSUE TITLE
Compile in AC6

### ISSUE THREAD

**Issue by wizz777** [sdima1357/specci48#1]
build/smain.o: In function `poke':
smain.c:(.text.poke+0x5c): undefined reference to `writeByte'
build/smain.o: In function `peek':
smain.c:(.text.peek+0x22): undefined reference to `readByte'
build/core.o: In function `LCD_exitStandby':
core.c:(.text.LCD_exitStandby+0xa): undefined reference to `dmaSendCmdCont'
core.c:(.text.LCD_exitStandby+0x18): undefined reference to `dmaSendCmdCont'
build/core.o: In function `LCD_setOrientation':
core.c:(.text.LCD_setOrientation+0x1e): undefined reference to `dmaSendCmdCont'
core.c:(.text.LCD_setOrientation+0x28): undefined reference to `dmaSendDataCont8'
build/core.o: In function `LCD_init':
core.c:(.text.LCD_init+0x4a): undefined reference to `dmaSendCmdCont'
core.c:(.text.LCD_init+0x52): undefined reference to `dmaSendDataCont8'
build/core.o: In function `LCD_setAddressWindow':
core.c:(.text.LCD_setAddressWindow+0xc): undefined reference to `dmaSendCmdCont'
core.c:(.text.LCD_setAddressWindow+0x1c): undefined reference to `dmaSendDataCont16'
core.c:(.text.LCD_setAddressWindow+0x22): undefined reference to `dmaSendCmdCont'
core.c:(.text.LCD_setAddressWindow+0x32): undefined reference to `dmaSendDataCont16'
build/core.o: In function `LCD_Write8x8line':
core.c:(.text.LCD_Write8x8line+0x12): undefined reference to `dmaSendCmdCont'
core.c:(.text.LCD_Write8x8line+0x24): undefined reference to `SPIx_WriteF'
core.c:(.text.LCD_Write8x8line+0x2c): undefined reference to `SPIx_WriteF'
core.c:(.text.LCD_Write8x8line+0x36): undefined reference to `SPIx_WriteF'
core.c:(.text.LCD_Write8x8line+0x42): undefined reference to `SPIx_ReadF'
build/core.o: In function `LCD_FullRect3':
core.c:(.text.LCD_FullRect3+0x1c): undefined reference to `dmaSendCmdCont'
core.c:(.text.LCD_FullRect3+0x2e): undefined reference to `SPIx_ReadF'
core.c:(.text.LCD_FullRect3+0x4a): undefined reference to `SPIx_WriteF'
core.c:(.text.LCD_FullRect3+0x50): undefined reference to `SPIx_WriteF'
core.c:(.text.LCD_FullRect3+0x56): undefined reference to `SPIx_WriteF'
build/core.o: In function `LCD_FullRect6':
core.c:(.text.LCD_FullRect6+0x20): undefined reference to `dmaSendCmdCont'
core.c:(.text.LCD_FullRect6+0x34): undefined reference to `SPIx_ReadF'
core.c:(.text.LCD_FullRect6+0x50): undefined reference to `SPIx_WriteF'
core.c:(.text.LCD_FullRect6+0x56): undefined reference to `SPIx_WriteF'
core.c:(.text.LCD_FullRect6+0x5c): undefined reference to `SPIx_WriteF'
core.c:(.text.LCD_FullRect6+0x62): undefined reference to `SPIx_WriteF'
core.c:(.text.LCD_FullRect6+0x68): undefined reference to `SPIx_WriteF'
build/core.o:core.c:(.text.LCD_FullRect6+0x6e): more undefined references to `SPIx_WriteF' follow
build/core.o: In function `LCD_fillRect':
core.c:(.text.LCD_fillRect+0x12): undefined reference to `color_convert'
collect2: error: ld returned 1 exit status
make: *** [build/spessi1.elf] Error 1

**Comment by sdima1357** [comment]
Can You send me your compiler version? I use 
>/usr/bin/arm-none-eabi-gcc --version
arm-none-eabi-gcc (15:4.9.3+svn231177-1) 4.9.3 20150529 (prerelease)

**Comment by wizz777** [comment]
/usr/local/bin/arm-none-eabi-gcc --version
arm-none-eabi-gcc (GNU Tools for Arm Embedded Processors 7-2017-q4-major) 7.2.1 20170904 (release) [ARM/embedded-7-branch revision 255204]
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by sdima1357** [comment]
Seems like Your compiler has problem with "inline" modificator. Try to remove it from undefined functions

**Comment by wizz777** [comment]
Thx I download arm gcc version 4.9 and all ok!

**Comment by sdima1357** [comment]
Anyway i remove all inline from the code, thanks
