### ISSUE TITLE
Memory Error 293 93

### ISSUE THREAD

**Issue by Airrr17** [sdima1357/specci48#2]
I have both versions of boards with 64K and 128K and both of them makes me the same error.
-Memory Error
-293
-93
after touching the screen:
-28
and for second time:
Memory Error
5B00
416 (415 sometimes)
On third touching appears list of files, even trying to load, but crashes.

Does it means my LCD's memory are corrupted?

Thank you!

**Comment by sdima1357** [comment]
"Does it means my LCD's memory are corrupted?" 
Seems like problem with read-back values from display.

1 Did You check 5/3.3 volt jumper on the LCD board???
2 Check connections - it uses common MISO,MOSI,SCKL for  touch,sd and lcd
3 Try to reduce system freq

**Comment by Airrr17** [comment]
After replacing dupont wires with soldered ones got much better:
OK
FFFFFFFF
92
-touch
28 (27)
-touch
OK
FFFFFFFF
413 (412)
Touching now shows filelist correctly, but can't load nothing.
Here is screenshoot of TETRIS2 game.
Sorry for the quality. Here is "TETR" (Я) three times or the right half of screen and "IS2" on the left.

Can you help please? :) thank you.

![s48](https://user-images.githubusercontent.com/38572664/45601095-e59a7b00-b9f6-11e8-8250-1af56745d680.jpg)

**Comment by sdima1357** [comment]
Send me Your game to my mail (sdima1357@gmail.com). I will try to fix it

**Comment by Airrr17** [comment]
It's not about this game especially. (TETRIS2.Z80)
every files z80 and tap are loading the similar way.
arkanoid, boulder dash, saboteur2, dizzy...
Here is a better screenshoot:
![resize of s48_](https://user-images.githubusercontent.com/38572664/45884153-a6777b80-bda2-11e8-919c-c5d250012f3b.jpg)

**Comment by sdima1357** [comment]
Format "tap" is not supported in this version from sdio. Format "z80" has a lot of modifications,without real file i can't try to debug it. Send me Your problematic file by email and i will try it, in some free time. I'am working on the  next version, it can take some time.

**Comment by sdima1357** [comment]
1 This game is for specci 128K (
    byte 34 in z80 file is 3
from spec z80 file https://www.worldofspectrum.org/faq/reference/z80format.htm

Value:          Meaning in v2           Meaning in v3
        -----------------------------------------------------
          0             48k                     48k
          1             48k + If.1              48k + If.1
          2             SamRam                  SamRam
          3             128k                    48k + M.G.T.
          4             128k + If.1             128k
          5             -                       128k + If.1
          6             -                       128k + M.G.T.

But anyway without sd card You have to see:

"@ 1982 Sinclair Research Ltd " on white background in black frame.

If You don't see it You have problem with stability. Try to reduce system freq by replace in main.c 
RCC_OscInitStruct.PLL.PLLMUL = RCC_PLL_MUL14; to 

RCC_OscInitStruct.PLL.PLLMUL = RCC_PLL_MUL9;  or something between 9 and 14

**Comment by Airrr17** [comment]
Thank you! I got it :) Now everything is working as it should! Great!
