### ISSUE TITLE
8 bit parallel?

### ISSUE THREAD

**Issue by astranome** [sdima1357/specci48#4]
What about port to ILI9341 8bit parallel ?
Maybe possible to run project on DSO138 scope (STM32F103C8T6+2.4 " ILI 9341 8bit parallel) ?

**Comment by sdima1357** [comment]
It is possible, but i have no hardware like this (DSO138 scope) , and have no time to simulate their configuration.
So, sorry...
I can send You code for "write" and "read back"  ILI9341 8bit (connected to PA0-PA7 pins) para display by mail, with more or less same functions, but it heavy uses dedicated pin map.
